name: Thank Contributor on Push

on:
  push:
    branches:
      - '**'  # Run on push to any branch

jobs:
  thank:
    runs-on: windows-latest

    steps:
    - name: Get contributor name
      run: |
        $actor = "${{ github.actor }}"
        Write-Host "Actor: $actor"
        
        if ($actor -eq "Madhavv-Xd") {
          Write-Host "Thanks for your contribution, Madhavv-Xd!"
        } elseif ($actor -eq "Lucky-2006-18") {
          Write-Host "Thanks for your contribution, Lucky-2006-18!"
        } else {
          Write-Host "Thanks for your contribution, $actor!"
        }
